Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
om.show_options_table("dymos.phase.options.TimeOptionsDictionary")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_22584/1678355375.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mom[0m[0;34m.[0m[0mshow_options_table[0m[0;34m([0m[0;34m"dymos.phase.options.TimeOptionsDictionary"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/usr/share/miniconda/envs/test/lib/python3.8/site-packages/openmdao/utils/notebook_utils.py[0m in [0;36mshow_options_table[0;34m(reference, recording_options)[0m
[1;32m    101[0m     [0;32mif[0m [0mipy[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    102[0m         [0;32mif[0m [0;32mnot[0m [0mrecording_options[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 103[0;31m             [0;32mreturn[0m [0mdisplay[0m[0;34m([0m[0mHTML[0m[0;34m([0m[0mobj[0m[0;34m.[0m[0moptions[0m[0;34m.[0m[0mto_table[0m[0;34m([0m[0mfmt[0m[0;34m=[0m[0;34m'html'[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    104[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    105[0m             [0;32mreturn[0m [0mdisplay[0m[0;34m([0m[0mHTML[0m[0;34m([0m[0mobj[0m[0;34m.[0m[0mrecording_options[0m[0;34m.[0m[0mto_table[0m[0;34m([0m[0mfmt[0m[0;34m=[0m[0;34m'html'[0m[0;34m)[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'TimeOptionsDictionary' object has no attribute 'options'
AttributeError: 'TimeOptionsDictionary' object has no attribute 'options'

